<?php 


$LANG = array(
    "tasktodo" => "Start Date",
    "addtask" => "Add Timeline",
    "task" => "Timeline",
    "daysopen" => "Days open",
    "duedate" => "Due date",
    "priority" => "Priority",
    "action" => "Action",
    "edit" => "Edit",
    "delete" => "Delete",
    "high" => "High",
    "normal" => "Normal",
    "low" => "Low",
    "onhold" => "On hold",
    "tasks" => "Tasks",
    "taskupdated" => "Task updated",
    "redirected" => "You will now be redirected back to the task list. <br /><a href=\"index.php\">If that does not happen, please click here.</a>",
    "eupdatetask" => "Error: Task could not be updated.",
    "etasknotfound" => "Error: Task not found.",
    "taskadded" => "Task added.",
    "etasknotadded" => "The task could not be added. Please check JSON permissions.",
    "taskdone" => "The task is marked as finished. ",
    "etasknotdone" => "Error: the task could not be marked as done. Please check JSON permissions. ",
    "etasknotdeleted" => "Error: the task could not be deleted. Please check JSON permissions.",
    "taskdeleted" => "The task is deleted.",
    "noactiongiven" => "Error: no correct action given. ",
    "thrash" => "Thrash Bin",
    "backtohomepage" => "Back to the main page",
    "tobin" => "Thrash Bin",
    "updatetask" => "Update task",
    "notasks" => "No tasks.",
    "todo" => "Timelines",
    "daysleft" => " days left",
    "dayslate" => " days late",
    "today" => "Today!",
    "infotext" => 'This is a task/todo list written in PHP. It uses a JSON text file for the tasks (<a href="task.json">click here to see it</a>) and the visual side is created with the <a href="http://99lime.com">excellent HTML5 Kickstart framework by Joshua Gatcke.</a><br />This script was written by <a href="https://raymii.org">Remy van Elst</a>.',
    "info" => "Info",
    "finishedtasks" => "Finished Tasks",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => ""

    );

?>